spring:
  datasource:
#    url: jdbc:h2:file:~/real_estate_database
#    schema:
#    username: sa
#    password: password
    url: jdbc:postgresql://localhost:5433/postgres_s
    user: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
#      ddl-auto: create-drop
  sql:
    init:
      mode: never
  flyway:
    enabled: true
#    enabled: false
#    url: jdbc:h2:file:~/real_estate_database
#    user: sa
#    password: password
    url: jdbc:postgresql://localhost:5433/postgres_s
    user: postgres
    password:
  h2:
    console.enabled: true
server:
  port: 8081